apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-385122
  artifacts:
    - image: onoja/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: onoja/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
